### ISSUE TITLE
API Key dialog missing input field

### ISSUE THREAD

**Issue by alanhamlett** [allista/WakatimeBlender#14]
Something must have changed in Blender version `2.93.0` and newer, because the dialog input field for entering api key is now missing:
<img width="312" alt="Screen Shot 2021-10-30 at 12 16 07 PM" src="https://user-images.githubusercontent.com/522344/139555856-8639e952-1ac3-4bee-99ff-806e236416de.png">

In Blender version `2.92.0` it looks correct:
<img width="318" alt="Screen Shot 2021-10-30 at 12 14 38 PM" src="https://user-images.githubusercontent.com/522344/139555870-47079e83-3115-4af9-8c85-75923f36a98f.png">

I'm not sure if this can be fixed by using [bpy.types.Operator](https://github.com/allista/WakatimeBlender/blob/3ca75541c8934eef80bae6cfb42e079ca3c8bb8a/WakaTime.py#L81) differently or if it's just a bug introduced into Blender 2.93.0.

**Comment by williamchange** [comment]
I was able to fix the issue by changing the [line](https://github.com/allista/WakatimeBlender/blob/3ca75541c8934eef80bae6cfb42e079ca3c8bb8a/WakaTime.py#L84) from:

```python
api_key = StringProperty(name="API Key")
```
to the following:
```python
api_key: StringProperty(name="API Key")
```

Which then the dialog input field shows up correctly:

Blender `2.93.5` LTS:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/830253/141777941-9d4f0aa7-add5-466f-aed6-d054ed7c1c87.png">

**Comment by MasterKrepta** [comment]
Has anyone had success modifying this to work in 3.0?

I have not been able to get it working yet myself.

**Comment by allista** [comment]
I'm working on the v2.0 for blender 2.93, which will fix all the current issues.

Once I'm done, I'll check its compatibility with blender 3.0
