### ISSUE TITLE
Non-functional in 2.93.6 (Steam)

### ISSUE THREAD

**Issue by simonSlamka** [allista/WakatimeBlender#15]
Hey,

The script is not working in the 2.93.6 release (latest at this time).

I am able to search for the API key field with the F3 search menu.

The solution proposed in the currently open PR doesn't solve the issue either - the plugin isn't even attempting to send heartbeats to WakaTime.

Blender itself is not reporting any issues and is running normally.

**Comment by williamchange** [comment]
This is due to the change of the file downloaded from https://github.com/wakatime/wakatime/archive/master.zip ([line 46](https://github.com/allista/WakatimeBlender/blob/master/WakaTime.py#L46)) at which now downloads to `legacy-python-cli-master.zip` so the script doesn't locate it properly

**Comment by simonSlamka** [comment]
Oh, yeah, forgot about the migration.

It's working now, thanks :-).
