### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DaCuteRaccoon** [allista/WakatimeBlender#17]
Zip installs fine, but enabling it, there is an error:
![image](https://user-images.githubusercontent.com/72467156/148430967-950d0e51-9f9a-49f5-b659-e96bf8bebe24.png)

**Comment by allista** [comment]
WakatimeBlender-2.0.0 is made for blender-2.93 and was not tested with earlier versions. So I suggest you to upgrade your blender installation to 2.93.

Still, I'll look into it, and if this is the only incompatibility, I'll fix it.

**Comment by allista** [comment]
Fixed the issue in the new release:

https://github.com/allista/WakatimeBlender/releases/tag/v2.0.1-b2.93

Please, download the .zip archive from the Releases section and confirm it's working.

**Comment by alanhamlett** [comment]
@DaCuteRaccoon is it working for you now?

**Comment by MasterKrepta** [comment]
I got an almost identical issue to this one last night with the 3.0 version. I did not have time to attempt to diagnose it.

**Comment by allista** [comment]
But you're on 2.91, so you have to use 2.9 (i.e. master) branch.

**Comment by MasterKrepta** [comment]
This is the error I am getting off a fresh install of the official release of Blender 3.0 (using the 2.0.1 for blender 3.0.0 release)

![image](https://user-images.githubusercontent.com/10622339/149039465-3ba4a353-c2d8-4f62-b68e-18b9b4be3a83.png)

**Comment by KennethVassbakk** [comment]
> This is the error I am getting off a fresh install of the official release of Blender 3.0 (using the 2.0.1 for blender 3.0.0 release)
> 
> ![image](https://user-images.githubusercontent.com/10622339/149039465-3ba4a353-c2d8-4f62-b68e-18b9b4be3a83.png)

An easy fix is to rename the folder within the script/addon to WakatimeBlender-2 (from WakatimeBlender-2.0.1-b3.0.0)

**Comment by MasterKrepta** [comment]
Thank you @KennethVassbakk That worked. I had renamed it  2.0 originally and that didn't work, but this did.

**Comment by DaCuteRaccoon** [comment]
> But you're on 2.91, so you have to use 2.9 (i.e. master) branch.

But how do I check my version of blender?

**Comment by BSoDium** [comment]
@DaCuteRaccoon click on the blender logo (top left) then <kbd>splash screen</kbd>. The blender version should be shown on top right corner of the newly opened window.
Thank you @KennethVassbakk that did work btw.

**Comment by DaCuteRaccoon** [comment]
Ok

**Comment by DoodleBears** [comment]
> > This is the error I am getting off a fresh install of the official release of Blender 3.0 (using the 2.0.1 for blender 3.0.0 release)
> > ![image](https://user-images.githubusercontent.com/10622339/149039465-3ba4a353-c2d8-4f62-b68e-18b9b4be3a83.png)
> 
> An easy fix is to rename the folder within the scripts\addons to WakatimeBlender-2 (from WakatimeBlender-2.0.1-b3.0.0)

Thank you. 
1. Just extract the .zip and copy the folder to **scripts/addons**
2. Rename the folder from [WakatimeBlender-2.0.1-b3.0.0] to [WakatimeBlender-2]
3. Refresh blender add-ons
4. Done

**Comment by Snailedlt** [comment]
Can confirm that renaming like this comment says fixes the issue.
https://github.com/allista/WakatimeBlender/issues/17#issuecomment-1013696126

@allista
Maybe you can update the release?

**Comment by allista** [comment]
Unfortunately, the name of the archive is generated by GitHub automatically, so the only way to work around this is to manually create release archives.

For now I've updated the README, including the renaming step.
