### ISSUE TITLE
error when using release for 3.0.0

### ISSUE THREAD

**Issue by apoleon33** [allista/WakatimeBlender#19]
When trying to enable the add-on after installing it via the .zip from the release section:

![image](https://user-images.githubusercontent.com/71031475/159556205-1c9df95d-9996-4187-9370-60dc648b7e8a.png)

Specs:
- Tested on blender 3.1.0 and 3.0.0: both not working
- Blender installed from steam
- OS: windows 11

**Comment by MasterKrepta** [comment]
https://github.com/allista/WakatimeBlender/issues/17#issuecomment-1013696126

The above comment solved the issue in 3.0 for me, however i have still not had any success getting the heartbeats to register on 3.1

**Comment by allista** [comment]
Unfortunately, the name of the archive is generated by GitHub automatically, so the only way to work around this is to manually create release archives.

For now I've updated the README, including the renaming step.

**Comment by apoleon33** [comment]
thanks !
