### ISSUE TITLE
3.1 Comptability

### ISSUE THREAD

**Issue by Yeikzy** [allista/WakatimeBlender#21]
![Image](https://i.imgur.com/VkLb0xh.png)

**Comment by williamchange** [comment]
This error could be resolved by renaming the folder, see https://github.com/allista/WakatimeBlender/issues/17#issuecomment-1013696126 for more details

Though there's a 3.1 compatibility issue due to python 3.10 https://github.com/allista/WakatimeBlender/issues/20

**Comment by Yeikzy** [comment]
> This error could be resolved by renaming the folder, see [#17 (comment)](https://github.com/allista/WakatimeBlender/issues/17#issuecomment-1013696126) for more details
> 
> Though there's a 3.1 compatibility issue due to python 3.10 #20

![Error](https://cdn.upload.systems/uploads/DiOYwBwm.png)
