### ISSUE TITLE
the 3.0 releases cannot be used whit 3.0

### ISSUE THREAD

**Issue by Dobby-progam** [allista/WakatimeBlender#22]
![afbeelding](https://user-images.githubusercontent.com/87517487/166687957-7d910b83-d943-4c68-81c0-9df4a73053c0.png)
I get this error when trying to enable it in 3.0

**Comment by VerzatileDev** [comment]
![image](https://user-images.githubusercontent.com/47317248/166928442-8caad57a-e5e7-4b99-aa3e-0ece8f36cf23.png)
Same seems to happen with Earlier versions between 2.0 - 3.0

**Comment by Yeikzy** [comment]
Same

**Comment by williamchange** [comment]
This should be resolved by renaming the folder, see https://github.com/allista/WakatimeBlender/issues/17#issuecomment-1013696126

**Comment by allista** [comment]
Unfortunately, the name of the archive is generated by GitHub automatically, so the only way to work around this is to manually create release archives.

For now I've updated the README, including the renaming step.
