### ISSUE TITLE
Blender 2.8 compatibility?

### ISSUE THREAD

**Issue by nassosyian** [allista/WakatimeBlender#3]
currently it is not compatible with version 2.8 and is being ignored.
please update it.

**Comment by allista** [comment]
Unfortunately, I don't have time to do it in foreseeable future -- too much work at work.

If you've some python skill, it should be really trivial to make necessary changes (if any) to make compatible. Otherwise, I'll come to that when I have enough time...

**Comment by allista** [comment]
Oh, and 2.8 is not yet released as stable. So I guess I'll wait until it is.

**Comment by jerry-sky** [comment]
@allista Blender 2.8 has officially come out. Will you be able to make your addon compatible with this new version of Blender?

**Comment by MasterKrepta** [comment]
I attempted to figure out what to change myself last night, but I am not a python-dev so I had no luck.

**Comment by MasterKrepta** [comment]
There seems to still be an issue. I just updated with the new file, but I cannot seem to enter the API key when I search for it the setting does not appear. 
![2019-08-11](https://user-images.githubusercontent.com/10622339/62835462-db90f480-bc26-11e9-9b0c-88224884262b.png)
![2019-08-11 (2)](https://user-images.githubusercontent.com/10622339/62835463-dcc22180-bc26-11e9-9b64-d39644f1ff3f.png)

**Comment by jerry-sky** [comment]
I've noticed that the Blender version wasn't updated in the plugin file. However, after manually changing the version from `(2, 77, 0)` to `(2, 80, 0)` in the addon file as the [Blender reference](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Addons) advises, it still isn't working. Following error is occurring while trying to turn on the addon:
![image](https://user-images.githubusercontent.com/4989529/62836027-24649f80-bc5f-11e9-871c-2e8178f9ffbc.png)

As I don't know anything about creating Blender addons I'm unable to mend it.

**Comment by allista** [comment]
Re-merged #5, tested it locally and fixed several other issues.
Now it does work with 2.80
