### ISSUE TITLE
4.x compatibility?

### ISSUE THREAD

**Issue by mrdarip** [allista/WakatimeBlender#30]
![image](https://github.com/user-attachments/assets/7ae3b0c5-b73b-449f-b2c1-12876eb66060)

will the project get 4.x compatibility?

**Comment by Mowen-M** [comment]
same problem

**Comment by MasterKrepta** [comment]
Not sure why mine is working, but I have 4.2 and my stats are recording just fine. 

The only thing I know i did back in the days of 3.0 was follow the steps in issue #17

**Comment by mrdarip** [comment]
yup that was it 
[solution](https://github.com/allista/WakatimeBlender/issues/17#issuecomment-1013696126)
