### ISSUE TITLE
No "waka" in search 

### ISSUE THREAD

**Issue by krau5** [allista/WakatimeBlender#9]
There was no window where I could enter my API key.
I've fully followed your instructions, although there is no "waka" in search.
Blender - 2.9
Ubuntu 20.04
![err](https://user-images.githubusercontent.com/52201020/96844023-ac475b80-1457-11eb-8cca-a22c168609df.jpg)

**Comment by Vrungar** [comment]
Same Here...
Blender - 2.90.1
Windows 10

**Comment by hannes-pj** [comment]
How did you download the python-file?

I right-clicked and used "Save Link As..." ... and all I got was HTML (in the file `WakaTime.py`! :cry: ).

So it is better to:
1. either clone the whole project, or
2. click on the python-file (within GitHub) and then "Save Link As ..." with the "Raw" data :+1: 

Direct link: https://github.com/allista/WakatimeBlender/raw/master/WakaTime.py

Blender 2.90.1
Linux Mint 20

**Comment by Krausso** [comment]
> 
> 
> How did you download the python-file?
> 
> I right-clicked and used "Save Link As..." ... and all I got was HTML (in the file `WakaTime.py`! 😢 ).
> 
> So it is better to:
> 
>     1. either clone the whole project, or
> 
>     2. click on the python-file (within GitHub) and then "Save Link As ..." with the "Raw" data 👍
> 
> 
> Direct link: https://github.com/allista/WakatimeBlender/raw/master/WakaTime.py
> 
> Blender 2.90.1
> Linux Mint 20

I did exactly the same. However that doesn't work

**Comment by hannes-pj** [comment]
> I did exactly the same. However that doesn't work

That's too bad. Sorry.
For me it worked, just today I downloaded the raw py-file and installed the plugin on a fresh Mint- and Blender-installation ... and it worked... and Mint being that close to Ubuntu ... strange :confused:

Is the `WakaTime.py` installed correctly under `~/.config/blender/2.90/scripts/addons`?
Whats the content of the file (python-code?)?

**Comment by williamchange** [comment]
I just created a pull request(a workaround) to add a field for the API key in the addon's preferences, it appears to work for me as I can see updates in my wakatime.
![image](https://user-images.githubusercontent.com/830253/101272424-b9d25e00-37d7-11eb-9242-3b19d44230ce.png)

**Comment by mekikula** [comment]
Does anybody has easy fix for this?

**Comment by mekikula** [comment]
Does anybody have an easy fix for this?

**Comment by srirahayu1981** [comment]
me too :(

**Comment by Krausso** [comment]
> I am using Blender 2.91 on Mac OS 11.0.1 and the search doesn't work for me.
> 
> I just created a pull request(a workaround) to add a field for the API key in the addon's preferences, it appears to work for me as I can see updates in my wakatime.
> ![image](https://user-images.githubusercontent.com/830253/101272424-b9d25e00-37d7-11eb-9242-3b19d44230ce.png)

I copied ur code, although that doesn't work for me. nt

**Comment by vikumDheemantha** [comment]
Same issue here. Installed without issue but there is no waka in search to add the API key.
I am using windows 10 and my blender version is 2.91

**Comment by allista** [comment]
The fix by @williamchange should indeed work. I'll recheck it and merge today.

Thanks for your reports.

**Comment by LoneDev6** [comment]
> 
> 
> The fix by @williamchange should indeed work. I'll recheck it and merge today.
> 
> Thanks for your reports.

Any news?

**Comment by SynthesisDu** [comment]
same issue
---blender Steam_App_ID: 365670
                  Steam_form_vid: 6915833
---Windows version 19043.1110 (21H1)

**Comment by allista** [comment]
The reason is that blender now shows in search only the operators registered in _some_ menu.

I'm working on the v2.0 of the plugin to fix all the current issues.
